version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
    default_reviewers:
      - "m7kvqbe1"
      - "thyhjwb6"

    default_labels:
      - "Type: Devops"
