on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: Royal-Navy/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GHA_UPNEXT_TOKEN }}"
        project-url: "https://github.com/orgs/Royal-Navy/projects/6"
        column-name: "Ready"
        label-name: "Status: Up next"
        columns-to-ignore: "Doing,Needs Review,Done"
